name: website

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - run: |
          npm install -g redoc-cli
          mkdir public
          redoc-cli bundle descriptions/keycloak-13.0.0.yaml -o public/index.html
          redoc-cli bundle https://raw.githubusercontent.com/ccouzens/keycloak-openapi/master/keycloak/11.0.json -o public/admin.html
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
